version: '2'

services:
  mysql:
    image: mysql
    ports:
      - 4381:3306
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bookhubdb"
    command: ["mysqld",
              "--character-set-server=utf8",
              "--collation-server=utf8_unicode_ci",
              "--init-connect='SET NAMES UTF-8;'",
              "--innodb-flush-log-at-trx-commit=0"]

  wildfly:
    build:
      context: ./web
    restart: on-failure
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 4380:8080
      - 4382:9990
